@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZqb2Jib2FyZC11c2VycyIsImlzcyI6ImRldmpvYmJvYXJkLmNvbSIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJqb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ3NDk1MTE3fQ.W-fpcxffPTsI0PSmOoyFUaWcVuN8-1ibms0DbgzCw88
@refreshToken = a2257ea4-baca-4043-8115-8bbcb62318b3

### Register a new user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "john",
  "password": "supersecret",
  "isAdmin": true
}

### Login to get tokens
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "supersecret"
}

### Refresh tokens (update tokens after login)
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout (update tokens after login)
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}
