@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZqb2Jib2FyZC11c2VycyIsImlzcyI6ImRldmpvYmJvYXJkLmNvbSIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJqb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzQ3NjQ3NjcwfQ.s9IIJAwVLOkwnm8nFycNFmgKHfCaiLn9Wrof-8Rgc8g
@refreshToken = 7f188ad6-42f1-4028-83fb-c8c53961bd3a

### Register a new admin
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "john",
  "password": "supersecret",
  "isAdmin": true
}

### Register a new user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "johnu",
  "password": "supersecret",
  "isAdmin": false
}

### Login to get tokens
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "supersecret"
}

### Refresh tokens (update tokens after login)
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout (update tokens after login)
POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}
